<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net6.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Autofac" Version="8.1.0" />
		<PackageReference Include="Autofac.Extensions.DependencyInjection" Version="10.0.0" />
		<PackageReference Include="JetBrains.Annotations" Version="2024.2.0" />

		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.1" />
	</ItemGroup>

	<!--Publish Package START-->
	<PropertyGroup>
		<PackageId>LTs.Autofac</PackageId>
		<Version>0.1.4</Version>
		<Authors>LTs</Authors>
		<Description>LTs.Autofac</Description>
		<Copyright>Copyright 2025</Copyright>
		<RepositoryUrl>https://github.com/LTsoft-repo/LTs.Package.Autofac.git</RepositoryUrl>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<DebugType>embedded</DebugType>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>
	<!--Publish Package END-->

</Project>